### ISSUE TITLE
cds deploy  Terminal command doesn't work. 

### ISSUE THREAD

**Issue by gsharan007** [SAP-samples/sap-devtoberfest-2020#63]
Dear Thomas,

I was going through CAP exercise -04 and was trying to deploy file data to SQLite DB but using command cds deploy I get error. In video I can see it works but not now. It could be due to some recent changes. Please let me know how to deploy file data to DB? 

user: bookshop $ cds deploy
[ERROR] Please specify a database kind or url, e.g.:

    cds deploy --to sql
    cds deploy --to sqlite
    cds deploy --to sqlite:db/my.db
    
    at Object.deploy (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/bin/deploy/index.js:63:44)
    at Object.exec (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/bin/cds.js:30:17)
    at Module.module.exports.Object.assign._ [as exports] (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/bin/cds.js:65:49)
    at Object.<anonymous> (/home/user/.node_modules_global/lib/node_modules/@sap/cds-dk/bin/cds.js:73:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

**Comment by maxstreifeneder** [comment]
Hi @gsharan007,

could you please try `cds deploy --to sqlite:bookshop.db`?

Cheers,
Max

**Comment by gsharan007** [comment]
Hi @maxstreifeneder ,

Thank you for quick reply, It worked ! 

Just wanted to know.. is there any way to deploy or move data from file to DB without using cds deploy? please advise.

Thanks
Gaurav

**Comment by jung-thomas** [comment]
@gsharan007 if you are deploying to HANA you can of course call the HDI Deployer directly without using cds deploy as well. That's really what the cds deploy is calling internally anyway.

**Comment by ahmedkhan29789** [comment]
Hello Experts, I am trying to create a SAP CAPM project and trying to deploy the cds artifact.

I am getting this error *"[ERROR] No .cds models found, please specify one as an argument"* when trying to run cds deploy --to sqlite, I also tried *unset NODE_PATH* still it didn't work, Any suggestion, please

I also tried giving full path of cds file still same error
*cds deploy --to sqlite:db/src/tables/promotions.cds*
